### ISSUE TITLE
(suggestion) colour theme config

### ISSUE THREAD

**Issue by Rodg88** [hilburn/AdvancedSystemsManager#17]
It would be cool to be able to change the colours ether in config or maybe in a gui in-game in the user prefs. (or possibly per manager)? Besides just being cool, it could also help when people need high contrast to read or are colourblind.

(and if nothing else, I think red for connection lines would be a nice default lol)

**Comment by hilburn** [comment]
This is something I've talked about doing a lot, and once the rest of the functional stuffis implemented i'll look into it

**Comment by goranalkovic** [comment]
As I agreed to help hilburn with the textures, I came up with an idea and already made concept images for this: real themes, not pure recolors.

For now, I made these concepts:
1) "Modern" theme, supports command recoloring, UI stays the same:
![gui1](https://cloud.githubusercontent.com/assets/2352553/7971500/61ab6c32-0a45-11e5-87fd-6940b0aa34d5.png)

2) Monochrome/colorblind theme: doesn't support command recoloring, but has 1 accent color applied thoughout the UI:
![gui2](https://cloud.githubusercontent.com/assets/2352553/7971496/5c9919ce-0a45-11e5-98cf-228f7456cef9.png)

3) Minecrafty-feeling theme, no recolors (some icons need to be worked on)
![gui3](https://cloud.githubusercontent.com/assets/2352553/7971492/58c1823c-0a45-11e5-9b84-9d9b6e5d4bea.png)

These are currently just images made in Photoshop, but everything is layered and I can really easily convert everything to images so it can be made into a sprite sheet.

---

BTW, @hilburn, why are you using my, now really old, SFM textures as a base? I made new ones for the Unity pack. I can send them to you if you want.

**Comment by way2muchnoise** [comment]
@goranalkovic :+1:

**Comment by hilburn** [comment]
@goranalkovic I'm using them because I quite like them - a fair bit more than the Unity ones actually.
As for these theme concepts - they are really cool and have some really nice aspects I'd like to integrate in, like having a desaturated version of the icon displayed on the command header - I think it looks great.
My idea for the themes was something along the lines of: https://github.com/hilburn/AdvancedSystemsManager/blob/master/src/main/resources/assets/advancedsystemsmanager/textures/gui/manager.png
As this will allow me to recolour the textures easily based on the theme file loaded by the user, which will have a bunch of colours assigned to things like so: http://pastebin.com/sZ8kznxj
I've got to head to bed now - but if you have a chance tomorrow if you could join on irc on #minechem I'd love to have a chance to discuss things with you more fully - the manager.png sheet I linked is really just for me to experiment with for now and am very open to changing it
Additionally there will be in-game theme editing, as I made this fancy colour-picker gui for creating new colours of Variables - and it frankly seems a waste not to use it as much as possible

![](http://g.recordit.co/iVhbexujx3.gif)

**Comment by goranalkovic** [comment]
See you on #minechem!
